//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Editor/EditorControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @EditorControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @EditorControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""EditorControls"",
    ""maps"": [
        {
            ""name"": ""CheatMenu"",
            ""id"": ""6ca2e8e4-3f43-4cd5-b779-6f7e3cb58f1e"",
            ""actions"": [
                {
                    ""name"": ""NextTurn"",
                    ""type"": ""Button"",
                    ""id"": ""7ac8c9a9-3840-436c-93e2-be1ad76a1bc3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Kill"",
                    ""type"": ""Button"",
                    ""id"": ""42f38d29-4903-4522-88d3-89c35ad987bb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MaxUpgradeUnit"",
                    ""type"": ""Button"",
                    ""id"": ""d98994e7-ae7f-4a1d-a6d6-ece2b3405e3b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2d4a5483-b0d1-4383-9bad-14f647e2473b"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextTurn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""78549c9f-0a52-4822-8b4f-c91d6b50891e"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Kill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""660f642d-6984-461f-9bfd-ebde792d4d25"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MaxUpgradeUnit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // CheatMenu
        m_CheatMenu = asset.FindActionMap("CheatMenu", throwIfNotFound: true);
        m_CheatMenu_NextTurn = m_CheatMenu.FindAction("NextTurn", throwIfNotFound: true);
        m_CheatMenu_Kill = m_CheatMenu.FindAction("Kill", throwIfNotFound: true);
        m_CheatMenu_MaxUpgradeUnit = m_CheatMenu.FindAction("MaxUpgradeUnit", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // CheatMenu
    private readonly InputActionMap m_CheatMenu;
    private List<ICheatMenuActions> m_CheatMenuActionsCallbackInterfaces = new List<ICheatMenuActions>();
    private readonly InputAction m_CheatMenu_NextTurn;
    private readonly InputAction m_CheatMenu_Kill;
    private readonly InputAction m_CheatMenu_MaxUpgradeUnit;
    public struct CheatMenuActions
    {
        private @EditorControls m_Wrapper;
        public CheatMenuActions(@EditorControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @NextTurn => m_Wrapper.m_CheatMenu_NextTurn;
        public InputAction @Kill => m_Wrapper.m_CheatMenu_Kill;
        public InputAction @MaxUpgradeUnit => m_Wrapper.m_CheatMenu_MaxUpgradeUnit;
        public InputActionMap Get() { return m_Wrapper.m_CheatMenu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CheatMenuActions set) { return set.Get(); }
        public void AddCallbacks(ICheatMenuActions instance)
        {
            if (instance == null || m_Wrapper.m_CheatMenuActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CheatMenuActionsCallbackInterfaces.Add(instance);
            @NextTurn.started += instance.OnNextTurn;
            @NextTurn.performed += instance.OnNextTurn;
            @NextTurn.canceled += instance.OnNextTurn;
            @Kill.started += instance.OnKill;
            @Kill.performed += instance.OnKill;
            @Kill.canceled += instance.OnKill;
            @MaxUpgradeUnit.started += instance.OnMaxUpgradeUnit;
            @MaxUpgradeUnit.performed += instance.OnMaxUpgradeUnit;
            @MaxUpgradeUnit.canceled += instance.OnMaxUpgradeUnit;
        }

        private void UnregisterCallbacks(ICheatMenuActions instance)
        {
            @NextTurn.started -= instance.OnNextTurn;
            @NextTurn.performed -= instance.OnNextTurn;
            @NextTurn.canceled -= instance.OnNextTurn;
            @Kill.started -= instance.OnKill;
            @Kill.performed -= instance.OnKill;
            @Kill.canceled -= instance.OnKill;
            @MaxUpgradeUnit.started -= instance.OnMaxUpgradeUnit;
            @MaxUpgradeUnit.performed -= instance.OnMaxUpgradeUnit;
            @MaxUpgradeUnit.canceled -= instance.OnMaxUpgradeUnit;
        }

        public void RemoveCallbacks(ICheatMenuActions instance)
        {
            if (m_Wrapper.m_CheatMenuActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICheatMenuActions instance)
        {
            foreach (var item in m_Wrapper.m_CheatMenuActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CheatMenuActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CheatMenuActions @CheatMenu => new CheatMenuActions(this);
    public interface ICheatMenuActions
    {
        void OnNextTurn(InputAction.CallbackContext context);
        void OnKill(InputAction.CallbackContext context);
        void OnMaxUpgradeUnit(InputAction.CallbackContext context);
    }
}
