//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/GameInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameInput"",
    ""maps"": [
        {
            ""name"": ""Game"",
            ""id"": ""4aff0585-8b89-4e8e-8592-cea52e81c9ad"",
            ""actions"": [
                {
                    ""name"": ""Restart"",
                    ""type"": ""Button"",
                    ""id"": ""fae20beb-dbf7-4a8e-be4f-1dc06dd3a749"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Menu"",
                    ""type"": ""Button"",
                    ""id"": ""d8c83e9d-5df8-43e4-9cba-b47626fbb55b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HorrorHeadRight"",
                    ""type"": ""Button"",
                    ""id"": ""5e86feef-636c-4d90-a29e-dff3a1de0c6e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HorrorWelcom"",
                    ""type"": ""Button"",
                    ""id"": ""e3829ec8-04a8-4bb5-a595-2c265b7b72a3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HorrorHeadLeft"",
                    ""type"": ""Button"",
                    ""id"": ""62aedbc1-4b00-4628-a31b-51604899d5e6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HorrorHeadLong"",
                    ""type"": ""Button"",
                    ""id"": ""999c14cf-726f-4e22-99e1-888fb78b7b1c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a45a3a8d-5493-41d1-93be-59cb37282c32"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Restart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a6b58f1b-df7a-4882-ae30-54a7a16bc01d"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Restart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""514e181f-2922-42cc-a29c-1690a4de5713"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3782a9be-c546-4d0f-b156-87b7cf712df4"",
                    ""path"": ""<Keyboard>/numpad6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorrorHeadRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f3fdc01f-772a-467c-be0d-af14544c184a"",
                    ""path"": ""<Keyboard>/numpad0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorrorWelcom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2ccd403d-9542-40b6-8717-bee5b1522a87"",
                    ""path"": ""<Keyboard>/numpad4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorrorHeadLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""abfcf45f-9d03-4fdd-ad7b-a364d475599b"",
                    ""path"": ""<Keyboard>/numpad8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorrorHeadLong"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Game
        m_Game = asset.FindActionMap("Game", throwIfNotFound: true);
        m_Game_Restart = m_Game.FindAction("Restart", throwIfNotFound: true);
        m_Game_Menu = m_Game.FindAction("Menu", throwIfNotFound: true);
        m_Game_HorrorHeadRight = m_Game.FindAction("HorrorHeadRight", throwIfNotFound: true);
        m_Game_HorrorWelcom = m_Game.FindAction("HorrorWelcom", throwIfNotFound: true);
        m_Game_HorrorHeadLeft = m_Game.FindAction("HorrorHeadLeft", throwIfNotFound: true);
        m_Game_HorrorHeadLong = m_Game.FindAction("HorrorHeadLong", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Game
    private readonly InputActionMap m_Game;
    private List<IGameActions> m_GameActionsCallbackInterfaces = new List<IGameActions>();
    private readonly InputAction m_Game_Restart;
    private readonly InputAction m_Game_Menu;
    private readonly InputAction m_Game_HorrorHeadRight;
    private readonly InputAction m_Game_HorrorWelcom;
    private readonly InputAction m_Game_HorrorHeadLeft;
    private readonly InputAction m_Game_HorrorHeadLong;
    public struct GameActions
    {
        private @GameInput m_Wrapper;
        public GameActions(@GameInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Restart => m_Wrapper.m_Game_Restart;
        public InputAction @Menu => m_Wrapper.m_Game_Menu;
        public InputAction @HorrorHeadRight => m_Wrapper.m_Game_HorrorHeadRight;
        public InputAction @HorrorWelcom => m_Wrapper.m_Game_HorrorWelcom;
        public InputAction @HorrorHeadLeft => m_Wrapper.m_Game_HorrorHeadLeft;
        public InputAction @HorrorHeadLong => m_Wrapper.m_Game_HorrorHeadLong;
        public InputActionMap Get() { return m_Wrapper.m_Game; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameActions set) { return set.Get(); }
        public void AddCallbacks(IGameActions instance)
        {
            if (instance == null || m_Wrapper.m_GameActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameActionsCallbackInterfaces.Add(instance);
            @Restart.started += instance.OnRestart;
            @Restart.performed += instance.OnRestart;
            @Restart.canceled += instance.OnRestart;
            @Menu.started += instance.OnMenu;
            @Menu.performed += instance.OnMenu;
            @Menu.canceled += instance.OnMenu;
            @HorrorHeadRight.started += instance.OnHorrorHeadRight;
            @HorrorHeadRight.performed += instance.OnHorrorHeadRight;
            @HorrorHeadRight.canceled += instance.OnHorrorHeadRight;
            @HorrorWelcom.started += instance.OnHorrorWelcom;
            @HorrorWelcom.performed += instance.OnHorrorWelcom;
            @HorrorWelcom.canceled += instance.OnHorrorWelcom;
            @HorrorHeadLeft.started += instance.OnHorrorHeadLeft;
            @HorrorHeadLeft.performed += instance.OnHorrorHeadLeft;
            @HorrorHeadLeft.canceled += instance.OnHorrorHeadLeft;
            @HorrorHeadLong.started += instance.OnHorrorHeadLong;
            @HorrorHeadLong.performed += instance.OnHorrorHeadLong;
            @HorrorHeadLong.canceled += instance.OnHorrorHeadLong;
        }

        private void UnregisterCallbacks(IGameActions instance)
        {
            @Restart.started -= instance.OnRestart;
            @Restart.performed -= instance.OnRestart;
            @Restart.canceled -= instance.OnRestart;
            @Menu.started -= instance.OnMenu;
            @Menu.performed -= instance.OnMenu;
            @Menu.canceled -= instance.OnMenu;
            @HorrorHeadRight.started -= instance.OnHorrorHeadRight;
            @HorrorHeadRight.performed -= instance.OnHorrorHeadRight;
            @HorrorHeadRight.canceled -= instance.OnHorrorHeadRight;
            @HorrorWelcom.started -= instance.OnHorrorWelcom;
            @HorrorWelcom.performed -= instance.OnHorrorWelcom;
            @HorrorWelcom.canceled -= instance.OnHorrorWelcom;
            @HorrorHeadLeft.started -= instance.OnHorrorHeadLeft;
            @HorrorHeadLeft.performed -= instance.OnHorrorHeadLeft;
            @HorrorHeadLeft.canceled -= instance.OnHorrorHeadLeft;
            @HorrorHeadLong.started -= instance.OnHorrorHeadLong;
            @HorrorHeadLong.performed -= instance.OnHorrorHeadLong;
            @HorrorHeadLong.canceled -= instance.OnHorrorHeadLong;
        }

        public void RemoveCallbacks(IGameActions instance)
        {
            if (m_Wrapper.m_GameActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameActions instance)
        {
            foreach (var item in m_Wrapper.m_GameActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameActions @Game => new GameActions(this);
    public interface IGameActions
    {
        void OnRestart(InputAction.CallbackContext context);
        void OnMenu(InputAction.CallbackContext context);
        void OnHorrorHeadRight(InputAction.CallbackContext context);
        void OnHorrorWelcom(InputAction.CallbackContext context);
        void OnHorrorHeadLeft(InputAction.CallbackContext context);
        void OnHorrorHeadLong(InputAction.CallbackContext context);
    }
}
