public enum EnumTextLocalization
{
    None,

    welcome_message,
    menu_start_button,
    menu_setting_button,
    menu_exit_button,
    menu_restart_button,
    menu_manual_button,
    menu_mainmenu_button,
    menu_continue_button,
    menu_back_button,
    setting_quality,
    setting_sounds,
    setting_game,
    setting_language,
    quality_verylow,
    quality_low,
    quality_medium,
    quality_high,
    quality_veryhigh,
    quality_ultra,
    sounds_units,
    sounds_modifications,
    sounds_ambient,
    sounds_other,
    game_dynamiccamera,
    game_madnessmode,
    game_immersiveobject,

    sushi,
    sushi_info,
    sushi_infotwo,
    sake,
    sake_info,

    win_menu,
    win_restart,

    ws_samurai,
    ws_ranger,

    ws_health,
    ws_damage,
    ws_attackrangesamurai,
    ws_attackrangeranger,
    ws_moverange,

    ws_modifi_damage,
    ws_modifi_attackdamage,
    ws_modifi_resistance,

    ws_eat_info_onetry,
    ws_eat_info_twotry,
}
